services:
  # ====================
  # BACKEND SERVICES
  # ====================

  products-service:
    build:
      context: ../backend/products
      dockerfile: Dockerfile
    env_file:
      - ../backend/products/.env
    volumes:
      - ../backend/products:/app
    container_name: products-service
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis
    networks:
      - backend-net
      - db-net


  # ====================
  # DATABASES
  # ====================
  postgres:
    image: postgres:15
    container_name: shop-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-shop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepass123}
      POSTGRES_DB: ${POSTGRES_DB:-shop}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

  redis:
    image: redis:7
    container_name: shop-redis
    command: redis-server --save 60 1 --loglevel warning --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - db-net

  # ====================
  # REVERSE PROXY
  # ====================
  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - postgres
      - redis
    networks:
      - frontend-net
      - backend-net

networks:
  db-net:
    driver: bridge
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  pgdata: